# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.provision "shell", path: "startup.sh"
  config.vm.define "basevm1" do |basevm1|
    basevm1.vm.box = "centos/7"
    basevm1.vm.hostname = "basevm1.eduami.org"
    basevm1.vm.network "private_network", ip: "192.168.50.10"
    basevm1.vm.provider "virtualbox" do |vb|
      vb.name = "basevm1"
      vb.memory = 8192
      vb.cpus = 1
    end
  end

end
